### ISSUE TITLE
If visitor enables UiPassword plugin, webpage css will be lost

### ISSUE THREAD

**Issue by cxgreat2014** [MuxZeroNet/ZeroMux#1]
```<link href="../../css/bootstrap-custom.min.css" rel="stylesheet" crossorigin="anonymous">```
if remove ` crossorigin="anonymous"` it works fine :smile: wish fix

**Comment by MuxZeroNet** [comment]
Docs updated. @cxgreat2014 check again please.

**Comment by cxgreat2014** [comment]
okay, I see :smile: thanks~
